language: php

# cache:
#   directories:
#     - $HOME/.composer/cache/files

php:
  # - 7.0
  # - 7.1
  - 7.2
  # - 7.3
  # - nightly

# services:
#   - mysql
  
# before_install:
#   - mysql -e 'CREATE DATABASE test CHARACTER SET utf8 COLLATE utf8_general_ci;'

# matrix:
#   allow_failures:
#     - php: nightly

# sudo: false

# install:
#   - if [[ "$BUILD" != true ]]; then
#       composer require satooshi/php-coveralls:~0.6@stable;
#     fi

# before_script:
#   - if [[ "$BUILD" != true ]]; then
#       mkdir -p build/logs;
#       git clone https://github.com/octobercms/october.git october/;
#       cd october;
#       composer install;
#       php artisan october:env;
#       sed -i "s/=database/=test/" .env;
#       php artisan october:up;
#       php artisan plugin:install Lovata.Toolbox;
#       cd ..;
#       mkdir -p ./october/plugins/lovata/shopaholic;
#       mv !(october) october/plugins/lovata/shopaholic;
#       FOLDER_PATH=$(pwd);
#       ln -s $FOLDER_PATH/october/plugins/lovata/ $FOLDER_PATH/october/tests/fixtures/plugins/lovata;
#       cd october/plugins/lovata/shopaholic;
#     fi

# script:
#   - ../../../vendor/bin/phpunit --coverage-clover build/logs/clover.xml

# after_success:
#   - if [[ "$BUILD" != true ]]; then
#       sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
#     fi

jobs:
  include:
    - stage: Release
      if: tag IS present
      env:
        - BUILD=true
      script:
        - NAME="shopaholic"
        - zip -r $NAME ./ -x .git/\* -x .gitignore -x .travis.yml -x crowdin.yml -x .editorconfig -x .codeclimate.yml -x PHPMD_custom.xml -x composer.json -x composer.lock -x vendor/\*
        - TAG=$(git describe --tags)
        - FILE="./$NAME.zip"
        - if [[ -e $FILE ]]; then
            NEW_NAME="$NAME-$TAG.$TRAVIS_JOB_ID";
            mv $NAME.zip $NEW_NAME.zip;
          fi
      deploy:
        provider: releases
        api_key:
          secure: RM899PrGQMg8ukFUBJMMSlZc8Dr5zMpC5XX/f3hDiIUSb/b/qxqknv47/XJF9sZ7fcLBlai/ji1zsoHJF5wXiiNwlHGDPeIGJ9oIBcacF5UgGkh1zXcrlwB2dJ0Eb5xV75qIrDhagjQnQLpTk85+FlAUhqvy2mFUzL2SxOtDP8S3dF7ZW+oR9DG4ypJZJJa7ufgeSeT3NBG/xesWCLgGiERPrNBSd+XcNNgQBK8WrFAOZFzOHBrMrtRdKylsE+cF8Dq5rWWln5tW7DpWKMvY/zWDisYa9+5H/3EW4sbCz+71fNZkybYdmKpoH7JYQ/A9aiIN3Mxs0VkgLUc/8fEUhDy/hvQNYhx/FHckAYff7fUvfdwprO3myHhOzTshmmXgKi0tj4K5Z0ZQ4O/p1l4eJZfUGRC/lNi4M8+oCmXM5mZH1nuQJ9ljCXd43JODUk7sHd4PAm3PRBR4y0MvWHD7S8jOPXFGfJWXCSmiBq+x84xrY1dG4KNngp1zoI0P9RxfkPu1o0lQ9bUUM6nbn/5yCd0uUK2qCUuqwSY7OTNgyv7DpUwIdJzkE50HzNPwoNXQqW7BB1buESmunlqird/YL7ked/+Xj7bfAqZM6bcmBDlE24u8/Mml4TcJo3IxPycc7TPQv4dpikYy53PF6oCEHkQdAEuvSphLmqxpM2nwtAI=
        file: "$NEW_NAME.zip"
        skip_cleanup: true
        on:
          tags: true
          repo: oc-shopaholic/oc-vk-goods-shopaholic-plugin
