plugin:
    name: 'lovata.vkgoodsshopaholic::lang.plugin.name'
    description: 'lovata.vkgoodsshopaholic::lang.plugin.description'
    author: Lovata
    icon: icon-vk
    homepage: ''
permissions:
    shopaholic-menu-vkgoodsshopaholic-export:
        label: 'lovata.vkgoodsshopaholic::lang.permission.vkgoodssettings'
        tab: 'lovata.shopaholic::lang.tab.permissions'
