plugin:
    name: 'lovata.vkontakteshopaholic::lang.plugin.name'
    description: 'lovata.vkontakteshopaholic::lang.plugin.description'
    author: Lovata
    icon: icon-upload
    homepage: ''
permissions:
